### ISSUE TITLE
Interpretation of 'active in the last year'

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/Civic_Programmer_Analyst_Skills_Task#1]
I can think of 2 possible interpretations of 'active in the last year', say on 8/1/2016:
- Opened or closed in the past year, i.e., date_opened > 7/31/2015 OR date_closed > 7/31/2015 (looks like date_completed is always blank).
- Had some sort of activity during the last year. I think this would mean that it has a record_status_date (or apparently equivalently date_statused) between 8/1/2015 and 7/31/2016. 

Which of these interpretations is correct? And is my understanding of the date fields correct?

**Comment by carlyleec** [comment]
The second option is correct. You should filter using either record_status_date or date_statused (They are always the same, I think???). This is actually an open issue on SimpliCity right now regarding how permits are filtered by time. Permits for large projects will often be opened long any visible is work actually done.
