### ISSUE TITLE
Interpretation of attributes

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/Civic_Programmer_Analyst_Skills_Task#2]
It would be helpful to have more explanation of various fields, if available - in a real project, I would have a conversation with the permitting folks to make sure I understand what they all represented. A few specific questions:
- record_module (which is seemingly duplicated by record_type_group) - values seem to be Permits, Planning and Services. Can I assume Permits=construction, Planning=planning, Services=code enforcement permits?
- job_value - only 2,070 of the 22,716 permits records opened or closed in the last year have a non-zero value (most of them 'Permits', but still only a fraction of those). Is this just haphazard entry or does a value signal something of interest?
- balance_due is usually zero (around 700 of the 22,716) - what does it actually signify? Fines? Fees? Should I care?

**Comment by carlyleec** [comment]
Alrighty...
1. @ejaxon you pretty much nailed record_module. Currently, we're only looking at Planning on SimpliCity, but would like it to include more run-of-mill permit statistics in the future. The record_type_type and record_type_subtype should be relevant as well (eg. we're only looking at record_module = Planning and record_type_type = Development on SimpliCity). I think this dashboard could really benefit from digging to these categories.
2. Just ignore job_value, I think it is only relevant to permits where the permit fee is contingent on the job value.
3. Ignore balance_due also, I'm pretty sure that this is set to zero once the fee has been paid. Let's ignore this field for this exercise.

We're really just look to answer generic big-picture questions like what, how many, where, when, etc.
