### ISSUE TITLE
User requirements

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/Civic_Programmer_Analyst_Skills_Task#3]
In an actual project one of my first steps would be to understand what the person using the dashboard is actually trying to accomplish - what decisions are they making, what actions are they taking, based on what they see. 

I am happy to speculate in building the tool, but thought it would be useful to at least ask: do you have any more specific requirements for what internal users are hoping to gain from a permitting dashboard?

**Comment by LiamDGray** [comment]
This! And the other issues by ejaxon are right on the mark, too.  Eliciting more clarity in requirements via use cases and term definitions is key.  In my experience, ejaxon is starting this project in the manner of someone who is going to win. :) May the best applicant win, but in any case, kudos to ejaxon. :)

**Comment by sbarnwell** [comment]
Great question. To be honest, we don't have detailed requirements at this point but know that there is a lot of interest among staff and in the broader community regarding trends and metrics in development and permitting. A big goal of this exercise (which will almost certainly develop into a real project) is to be proactive and start telling stories based on the data and trends in the data. We are looking at this as a way to put something on the table to generate further conversation.

Bonus points to ejaxon for asking and to LiamDGray for a sense of humor!
