### ISSUE TITLE
Where questions

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/Civic_Programmer_Analyst_Skills_Task#4]
In a previous answer, @carlyleec, you said that we want to answer "big-picture questions like what, how many, where, when, etc.".

Given my current lack of GIS skills (hoping not to have to become an expert in that by next week), I'm not planning to have a map or anything, but it would be nice at least to be able to present information by neighborhood or something like that. If there are definitions somewhere of the geometries of Asheville neighborhoods, I can presumably figure out a way to assign records to neighborhoods. Can you point me to such a thing (or give us a hint of a different way to do it)?

**Comment by carlyleec** [comment]
Those big-picture questions were just suggestions... don't feel like you need to answer them all. Play to your strengths. 

> Keep it simple. We are not looking for a finished product but want to learn about your skills and how you approach problems. Think of your delivery as something “minimal” that is on the road to awesome.

Having said that... neighborhood data in the city is a little arbitrary and not contiguous...BUT if you wanted to use it, its on the Open Data Portal. You can use the ArcGIS REST API to query permit points inside of neighborhood polygons. 

[Link to Neightborhood Data on the Open Data Portal](http://data.ashevillenc.gov/datasets/3450b18c20bf432eb8db7a002e631046_0)
