### ISSUE TITLE
API is down today

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/Civic_Programmer_Analyst_Skills_Task#5]
The API has been down all day today (that includes the table & query pages on the portal and the REST API itself).

I had a download of the original dataset so I wrote a script to extract a test set of records that meet the date restrictions and output in the form the API would have returned it.

@LiamDGray: Happy to share that if you need. Hard to compete without the data to play with :). You can find it at https://github.com/ejaxon/Civic_Programmer_Analyst_Skills_Task/blob/master/app/state/actions/sampleData.js. I've only included a subset of the fields, but I think it's everything we need. Let me know if you need anything more.  I'd share the downloaded file, but it's something like 1/2 GB.

**Comment by LiamDGray** [comment]
Many thanks, Eric! :)

**Comment by ejaxon** [comment]
Let me know if you need something different (more records or different fields). Not hard at this point to modify the script.

**Comment by carlyleec** [comment]
I got just got back to civilization. It looks like all of our ArcGIS REST services are down. Trying to figure out whats going on right now.

**Comment by carlyleec** [comment]
Looks like something is really wrong with our ArcGIS REST services. Restarting everything has fixed anything. In the meantime, here's a link to the ArcGIS REST API that SimpliCity uses in production for the permit data. It's the same data that was available through the Open Data Portal, but just from a different server:

http://arcgis-arcgisserver1-1222684815.us-east-1.elb.amazonaws.com/arcgis/rest/services/opendata/FeatureServer/1/query

**Comment by sbarnwell** [comment]
Thanks Cameron! I am just getting back to the online world myself since
yesterday morning. Looks like you've got a good workaround for the
exercise. Looks like a busy Monday morning awaits!

**Comment by ejaxon** [comment]
Hey @carlyleec, I'm using the new server, but it is acting differently than the previous one (could be my stupidity since I haven't used ArcGIS at all). I quickly figured out that the JSON format is slightly different - it puts all the attributes in an "attributes" sub-object rather than merged into the top level). And either it ignores resultRecordCount in the query or I don't understand what it means since I set it to 1000, but the api returns 10000 records at a time.

The main issue, however, is that when I ask for a count, I get 37094, but when I ask for the records themselves (using resultOffset to page through), it keeps going long past that (I killed it last time at about 150K records).

Here's the fetch I do for the count:

http://arcgis-arcgisserver1-1222684815.us-east-1.elb.amazonaws.com/arcgis/rest/services/opendata/FeatureServer/1/query?where=(record_status_date%20%3E%20date%20%272015-07-25%27%20AND%20%20record_status_date%20%3C%3D%20date%20%272016-07-25%27)&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=record_name,date_opened,record_status,record_status_date,record_type,record_type_group,record_type_category,record_type_type,record_type_subtype,latitude,longitude&returnGeometry=false&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=true&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=true&resultOffset=&resultRecordCount=1000&f=json

And here's an example records fetch (the 2nd one, after the first returns 10000 records):

http://arcgis-arcgisserver1-1222684815.us-east-1.elb.amazonaws.com/arcgis/rest/services/opendata/FeatureServer/1/query?where=(record_status_date%20%3E%20date%20%272015-07-25%27%20AND%20%20record_status_date%20%3C%3D%20date%20%272016-07-25%27)&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=record_name,date_opened,record_status,record_status_date,record_type,record_type_group,record_type_category,record_type_type,record_type_subtype,latitude,longitude&returnGeometry=false&returnTrueCurves=false&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=true&resultOffset=10000&resultRecordCount=1000&f=json

Any idea what I'm missing here?

Eric

**Comment by sbarnwell** [comment]
Sorry about the API issues. We are dealing with a pretty significant outage at the moment and are working to get everything restored. For the purpose of the skills task, feel free to make any assumptions that you need to make and just document them. We are definitely less concerned about "data accuracy" and more interested in the visualization and interpretation. We hope to have the API functioning again later today but feel free to make any necessary assumptions.

And PLEASE keep in mind that we are not expecting an epic effort or a totally finished product. Think MINIMAL but something that has the potential to be further developed into a finished product. Thanks!

**Comment by sbarnwell** [comment]
API (and other GIS services) are back up again. Sorry for the problems. Feel free to stick with the SimpliCity API that Cameron sent previously or whatever works best.
