### ISSUE TITLE
Interpretation of attributes, iteration 2 - hierarchy natural order

### ISSUE THREAD

**Issue by ejaxon** [cityofasheville/Civic_Programmer_Analyst_Skills_Task#6]
The main category attributes that seem interesting are:
- _record_type_group_ (= _record_module_): this is the one that signifies construction (permit) planning (planning) or enforcement (services).
- _record_type_: some typical values are remodel, site work, addition, etc.
- _record_type_type_: typical values are commercial, residential, fire, stormwater
- _record_type_subtype_: often duplicates _record_type_, but not always. Typical values: trade, site work, construction, remodel

The field names are, as usual, less than illuminating, but my inclination is to treat _record_type_group_ as an independent top-level category. I would then do one of two things:
- Consider [_record_type_type_, _record_type_, _record_type_subtype_], in that order, as a hierarchy (even though the names sort of imply a different order) OR
- Make _record_type_type_ another independent top level category and treat [_record_type_, _record_type_subtype_] as a hierarchy.

Do you have any information that would illuminate whether this makes sense or not?

**Comment by ejaxon** [comment]
Forgot to mention _record_type_category_, which is often similar to _record_type_.  There appears to be a lot of overlap between the meanings of the different fields and it's quite difficult to tell how to interpret their relationships to one another.

**Comment by ejaxon** [comment]
As an aid, here are the breakdowns of values for the different columns for all permits active in the last year (the number in parentheses is the total number of category values; the number following each category value is the count of permits with that value):

# Total records:  5605

(125) record_type :  {'Subdivision Recombination': 23, 'Com: Reroof': 33, 'Major Work': 9, 'Com: Plumbing': 98, 'Com:Addition': 14, 'Res: New': 86, 'RSWO': 1, 'Zoning Enforcement': 15, 'ROW: Encroachment': 23, 'Com: Multi-Family': 47, 'Outdoor Merchandise': 1, 'Conditional Zoning Permit': 2, 'Colocation': 6, 'Variance Zoning': 1, 'Res: Mod SFD': 4, 'Temp Utilities': 4, 'Com: Addition': 12, 'Com: Misc. Structure': 9, 'Res: Solar': 9, 'Com: Bldg Damage': 2, 'Push Cart': 2, 'Com: Emergency Repairs': 1, 'ZOE: Land Use Case': 4, 'Com: Landlord Impr': 25, 'Res: Alter & Add': 56, 'Res: New SFD': 194, 'Minor Subdivision': 34, 'Com: Shell': 2, 'Exhaust Hood': 9, 'Res: Emergency Repairs': 1, 'Com: Swimming Pool': 1, 'Refrigeration': 11, 'CSWO': 1, 'Res: Bldg Repair-Replace': 60, 'Fire: Occupational': 1, 'Flexible Development': 4, 'Planning Level III': 2, 'Com: Occupancy': 25, 'Com: Alterations': 278, 'Stand Alone Sign': 139, 'Planning Signage Plan': 1, 'Sprinkler Sys.': 76, 'Res: Reroof': 5, 'Res: Addition': 35, 'Permits/Stormwater/Operations & Maintenance/NA': 1, 'Res: Change Out': 1, 'Com: Gas Piping': 34, 'Res: Accessory Structure': 61, 'Outdoor Dining': 16, 'Com: FMO Enf Case': 1, 'Res: Electrical': 266, 'Project Inquiry': 3, 'Com: Multi-Trade': 79, 'Com: Modular': 2, 'Mfg. Home in Park': 37, 'ZOE: Other': 8, 'Fire Alarm': 63, 'Fire Prevention': 146, 'Work After Hours': 5, 'Variance Appeal': 2, 'Com: Mechanical': 97, 'Res: Plumbing': 222, 'Stormwater Enforcement': 4, 'Res: Site Work': 326, 'Com: Remodel': 138, 'Bond - LOC': 5, 'Res: Home Occupation': 4, 'Res: Alterations': 189, 'Alternative Compliance': 4, 'Com: Retaining Wall': 1, 'Com: Upfit': 3, 'Res: Remodel': 96, 'Research Zoning Letters': 39, 'Res: Retaining Wall': 5, 'Major Subdivision': 2, 'Com: Electrical': 243, 'A-Frame Sign': 30, 'Res: Bldg Damage': 3, 'Minor Work': 43, 'Res: Demolition': 13, 'Com: Site Work': 47, 'Flood': 69, 'Com: Detatched Bldg': 11, 'Com: First Upfit': 32, 'Variance Sign': 2, 'ZOE: Junked Vehicles': 8, 'ZOE: Sign Violation': 7, 'Res: Multi-Trade Heating': 334, 'Early Assistance': 22, 'Home Stay': 27, 'Conditional Zoning': 3, 'Res:Addition': 52, 'Res: Gas Piping': 108, 'Com: Multi-Trade Heating': 107, 'Com: Alter & Add': 9, 'Planning Level I': 63, 'Com: Bldg': 19, 'Com: Construction Staging': 2, 'Com: Low Voltage': 1, 'Construction Trailer': 4, 'Com: Other New': 14, 'Res: Mfg. Home': 4, 'Res: Multi-Trade': 443, 'Sign: Temp-Banner': 11, 'Fire: Operational': 18, 'Res: Deck': 41, 'Occupancy': 2, 'Foster Care': 5, 'ABC': 20, 'Lot Research': 5, 'Com: Annual Maint.': 29, 'Planning Level II': 3, 'Sign: Face Change': 2, 'Com: Accessory Structure': 21, 'Com: Warm Shell': 24, 'Com: Demo': 40, 'Cell Tower': 3, 'Res: Detached Bldg': 36, 'Event-Temporary Use': 64, 'Com: Bldg. Repair-Replace': 58, 'Res: Housing Case': 1, 'ZOE: Short Term Rental': 23, 'Res: Mechanical': 236, 'Fire: Hood Sys.': 15, 'Com: Solar Array': 2}

(3) record_type_group: {'Planning': 247, 'Permits': 5255, 'Services': 103}

(52) record_type_category :  {'SFD': 194, 'Mechanical': 333, 'Deck': 41, 'Plumbing': 320, 'Low Voltage Electrical': 1, 'Alterations': 467, 'Damage - Incident': 5, 'Telecom Colocation': 6, 'Landlord Improvements': 25, 'Sprinkler System': 76, 'Solar Array': 11, 'FMO Referral': 1, 'Telecom Tower': 3, 'Alterations w Addition': 65, 'Swimming Pool': 1, 'Junked Vehicles': 8, 'Reroof': 13, 'CO': 2, 'Home Stay': 27, 'Modular': 2, 'Other Referral': 8, 'Single Tenant': 19, 'Other': 70, 'Fire Alarm': 63, 'Addition': 66, 'Multi-Trade': 963, 'Short Term Rental': 23, 'NA': 1624, 'Exhaust Hood': 9, 'Like for Like': 25, 'Warm Shell': 24, 'Stop Work Order': 2, 'Residential': 1, 'Multi-Family': 47, 'Gas Piping': 142, 'Change Out': 1, 'Repair-Replacement': 118, 'Housing Code Referral': 1, 'Existing Park': 37, 'Accessory Structure': 21, 'Modular SFD': 4, 'Retaining Wall': 6, 'Sign Violation': 7, 'Hood Suppression': 15, 'Commercial': 1, 'Electrical': 509, 'Upfit First Occupancy': 32, 'Refrigeration': 11, 'Upfit': 3, 'Fire Prevention': 146, 'Land Use': 4, 'Shell Only': 2}

(18) record_type_type :  {'Fire': 319, 'HRC': 52, 'Outdoor Vendor': 19, 'Non Development': 4, 'Development': 79, 'Event-Temporary Use': 64, 'Subdivision': 59, 'Flexible Development': 4, 'Residential': 2950, 'Research': 44, 'Commercial': 1565, 'Project Inquiry': 25, 'Complaint-Enforcement': 78, 'Right of Way': 23, 'Sign': 182, 'Over The Counter': 63, 'Stormwater': 70, 'Variance': 5}

(54) record_type_subtype :  {'Demolition': 53, 'Home Occupation': 31, 'Flood Plain Development': 69, 'A-Frame': 30, 'Minor Work': 43, 'Trade': 2289, 'NA': 71, 'Construction Staging': 2, 'New Building': 300, 'Remodel': 234, 'Construction': 300, 'Merchandise': 1, 'Existing Building': 754, 'Major': 2, 'Meeting Request': 22, 'Encroachment': 23, 'Foster Care': 5, 'Accessory Structure': 185, 'Zoning Letters': 39, 'Minor': 34, 'Bond_LOC': 5, 'New': 148, 'Operations & Maintenance': 1, 'Emergency Repairs': 2, 'Face Change': 2, 'Residential Bldg': 5, 'Tenant Occupancy': 27, 'Level III': 2, 'Commercial Bldg': 4, 'Stormwater': 4, 'Lot': 5, 'Push Cart': 2, 'Annual Maintenance': 29, 'Zoning': 66, 'Level II': 3, 'Dining': 16, 'Stand Alone': 139, 'Level I': 63, 'Temp Utilities': 4, 'Construction Trailer': 4, 'Signage Plan': 1, 'Conditional Zoning': 5, 'Appeal': 2, 'Occupational': 19, 'Reroof': 25, 'Manufactured Home': 41, 'Temporary': 11, 'Site Work': 373, 'Work After Hours': 5, 'Addition': 47, 'Major Work': 9, 'ABC': 20, 'Recombination': 23, 'Alternative Compliance': 4, 'Sign': 2}

**Comment by carlyleec** [comment]
It is difficult to interpret the relationship between the fields, and thats part of what this exercise is about. 

Just do the best you can ...

I just ran a few queries, and this is my best guess (in decreasing hierarchy): 
record_type_group >> record_type_type >> record_type >> record_type_subtype
